[build]
  publish = "public"
  command = ""

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/assistente"
  to = "/.netlify/functions/assistente"
  status = 200
